from django.urls import path

from . import views

urlpatterns = [
    path("", views.article_list, name="article_list"),
    path(
        "articles/create/",
        views.create_article,
        name="create_article",
    ),
    path(
        "articles/pending/",
        views.pending_articles,
        name="pending_articles",
    ),
    path(
        "articles/<int:article_id>/approve/",
        views.approve_article,
        name="approve_article",
    ),
    path(
        "publishers/",
        views.publisher_list,
        name="publisher_list",
    ),
    path(
        "publishers/<int:publisher_id>/subscribe/",
        views.subscribe_publisher,
        name="subscribe_publisher",
    ),
    path(
        "publishers/<int:publisher_id>/unsubscribe/",
        views.unsubscribe_publisher,
        name="unsubscribe_publisher",
    ),
    path(
        "journalists/",
        views.journalist_list,
        name="journalist_list",
    ),
    path(
        "journalists/<int:journalist_id>/subscribe/",
        views.subscribe_journalist,
        name="subscribe_journalist",
    ),
    path(
        "journalists/<int:journalist_id>/unsubscribe/",
        views.unsubscribe_journalist,
        name="unsubscribe_journalist",
    ),
    path(
        "my-feed/",
        views.subscribed_articles,
        name="subscribed_articles",
    ),
    path(
        "newsletters/create/",
        views.create_newsletter,
        name="create_newsletter",
    ),
    path(
        "newsletters/",
        views.newsletter_list,
        name="newsletter_list",
    ),
    path(
        "newsletters/<int:newsletter_id>/",
        views.newsletter_detail,
        name="newsletter_detail",
    ),
    path(
        "articles/<int:article_id>/edit/",
        views.edit_article,
        name="edit_article",
    ),
    path(
        "articles/<int:article_id>/delete/",
        views.delete_article,
        name="delete_article",
    ),
    path(
        "newsletters/<int:newsletter_id>/edit/",
        views.edit_newsletter,
        name="edit_newsletter",
    ),
    path(
        "newsletters/<int:newsletter_id>/delete/",
        views.delete_newsletter,
        name="delete_newsletter",
    ),
    path(
        "api/articles/",
        views.api_article_list,
        name="api_article_list",
    ),
    path(
        "api/articles/subscribed/",
        views.api_subscribed_articles,
        name="api_subscribed_articles",
    ),
    path(
        "api/articles/<int:article_id>/",
        views.api_article_detail,
        name="api_article_detail",
    ),
]
