# Generated by Django 6.1.1 on 2026-10-04 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_publisher'),
        ('news', '0003_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribe_journalists',
            field=models.ManyToManyField(blank=True, related_name='reader_subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribe_publishers',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='news.publisher'),
        ),
    ]
