# Generated by Django 6.1.1 on 2026-10-06 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_subscribe_journalists_user_subscribe_publishers'),
        ('news', '0003_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='subscribe_journalists',
            new_name='subscribed_journalists',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='subscribe_publishers',
            new_name='subscribed_publishers',
        ),
        migrations.AlterField(
            model_name='user',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='news.publisher'),
        ),
    ]
